<template>
    <!-- Splash -->
  <v-container fluid class="splash">
    <div class="splash-centered mx-auto my-auto">
      <h1 style="text-align:center;padding-top:10vh">How to Value a <span class="primary-text">Company</span></h1>

<h6 align=center style="padding-top:5vh">Discounted Cash Flow Valuation </h6>

<div align=center style="padding-top:2vh;padding-right:10vh;padding-left:10vh;padding-bottom:10vh">

<p>
To forecast the separate line-items, in order to create a DCF model, there are several possible techniques that can be utilized. 
</p>

<p style="padding-top:2vh">
This website shows the growth rates assumed for each year on each stock’s page. 
</p>

<p style="padding-top:2vh">
After forecasting, one needs to calculate free cash flow for each period. 
</p>

<p style="padding-top:2vh">
This is calculated by doing: NOPAT – change in working capital + depreciation & amortization – capital expenditures.
</p>

<p style="padding-top:2vh">
Then, the terminal value is calculated by doing [ FCF year 5 X (1 + long-term growth rate) ] / (WACC – long-term growth rate)
</p>

<p style="padding-top:2vh">
  FCF= free cash flow generated by the firm 
</p>

<p>
WACC= weighted average cost of capital
</p>

<p>
WACC= cost of equity X (equity / (equity + net debt) ) + cost of debt X (debt / (equity + debt) ) X (1 – margin tax rate)
</p>

<p>
Cost of equity= risk free rate + (market return – risk free rate) X beta
</p>

<p>
Cost of debt= YTM on company’s debt
</p>

<p>
Risk free rate= US treasury bond (10 year or 30 year)
</p>

<p>
Beta= volatility of the stock relative to the market (the market has a beta of 1)
</p>

<p>
Each forecasted cash flow and terminal value is then discounted to present value using WACC.
</p>

<p>
Each PV is summed up which gives the stock’s Enterprise Value.
</p>

<p>
Enterprise Value – total debt + cash & equivalents = equity value
</p>

<p>
Equity value / total shares outstanding = expected share price.
</p>

<p>
Because forecasts can never be 100% accurate, a sensitivity analysis is then conducted by calculating share price with more conservative assumptions (higher WACC & lower long-term growth rate) and more aggressive assumptions (lower WACC & higher long-term growth rate). This gives us a range of prices one should expect a stock to trade at. However, that does not mean a stock will always be in the range as there are many factors influencing price movements. 
</p>
</div>

    </div>
  </v-container>
</template>

<script>
export default {
    data() {
        return {

        }
    }
}
</script>

<style scoped>

</style>