<template>
  <trading-vue :data="chart" 
   title-txt="BTCUSD">
 <!-- :width="width" 
  :height="height"
       
         :toolbar="true"
        :overlays="overlays"
        :color-back="colors.back"
        :color-grid="colors.grid"
        :color-text="colors.text"
        :color-title="colors.tvTitle" -->
        
        
    </trading-vue>
</template>

<script>
import { DataCube } from 'trading-vue-js' // DataCube helper
import Data from '~/assets/data.json'              // Sample Data (BTC price in this example)
//import TestOverlay from '~/components/TestOverlay' // Custom overlay

export default {
 //   props: ['width', 'height'], // Props generated by the TVJS engine
    data() {
        return {
            chart: new DataCube(Data),    // Wrap data into DataCube & plug-in it into TVJS
            // overlays: [TestOverlay],
            // colors: {
            //     back: '#121827',
            //     grid: '#3e3e3e',
            //     text: '#35a776',
            //   	cross: '#dd64ef',
            //   	candle_dw: '#e54077',
            //   	wick_dw: '#e54077',
            //     tvTitle: '#888'
            //}
        }
    }
}
</script>

<style>

</style>